title: LRF test site
description: Just a little test of the Github Pages functionality

remote_theme: pages-themes/primer@v0.6.0
plugins:
- jekyll-remote-theme

readme_index:
  enabled:          false
  remove_originals: false
  with_frontmatter: false

defaults:
  - scope:
      path: "_posts"
    values:
      layout: post
