title: LRF test site
description: Just a little test of the Github Pages functionality

theme: minima

paginate: 5
paginate_path: "/page:num/"

readme_index:
  enabled:          false
  remove_originals: false
  with_frontmatter: false

defaults:
  - scope:
      path: "_posts"
    values:
      layout: post

gems:
  - jekyll-paginate
